[build]
  command = "npm run netlify-build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NEXT_FORCE_EDGE_IMAGES = "true"
  NODE_VERSION = "18.17.0"
