[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"
  NEXT_PUBLIC_BASE_URL = "https://notebook-store.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/_ipx"
  status = 200
  force = true
  conditions = {Path = ["/api/auth/**"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
