import { Product } from '@/types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic Ruled Notebook',
    description: 'Premium quality ruled notebook with 200 pages of acid-free paper. Perfect for daily notes and journaling.',
    price: 12.99,
    images: [
      '/pics/marissa-grootes-BJ_BMDHjxhc-unsplash.jpg',
      '/pics/joanna-kosinska-I3adKpDNAjM-unsplash.jpg',
    ],
    category: 'ruled',
    features: ['Acid-free paper', 'Hardcover', '200 pages', 'Bookmark ribbon', 'Elastic closure'],
    stock: 45,
    createdAt: new Date('2023-01-10'),
    updatedAt: new Date('2023-01-10'),
  },
  {
    id: '2',
    name: 'Minimalist Dot Grid Journal',
    description: 'Sleek dot grid notebook with 160 pages. Ideal for bullet journaling, sketching, and planning.',
    price: 16.99,
    images: [
      '/pics/eugene-chystiakov-wcMysLw5ROM-unsplash.jpg',
      '/pics/kelly-sikkema-9OGNpJPVMZ8-unsplash.jpg',
    ],
    category: 'dot-grid',
    features: ['Dot grid pattern', 'Lay-flat binding', '160 pages', 'Pocket at back', '100gsm paper'],
    stock: 32,
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2023-01-15'),
  },
  {
    id: '3',
    name: 'Professional Sketchbook',
    description: 'High-quality blank sketchbook with 120 pages of 160gsm paper. Perfect for artists and designers.',
    price: 24.99,
    images: [
      '/pics/aaron-burden-AXqMy8MSSdk-unsplash.jpg',
      '/pics/aaron-burden-xG8IQMqMITM-unsplash.jpg',
    ],
    category: 'sketch',
    features: ['160gsm paper', 'Blank pages', '120 pages', 'Hardcover', 'Suitable for multiple media'],
    stock: 18,
    createdAt: new Date('2023-01-20'),
    updatedAt: new Date('2023-01-20'),
  },
  {
    id: '4',
    name: 'Pocket Daily Planner',
    description: 'Compact daily planner with monthly and weekly views. Perfect for organizing your busy schedule.',
    price: 18.99,
    images: [
      '/pics/kelly-sikkema-dgVSuJu58C0-unsplash.jpg',
      '/pics/beechmore-books-ZGMmMDu6P6s-unsplash.jpg',
    ],
    category: 'planner',
    features: ['Daily, weekly, and monthly views', 'Pocket size', 'Task lists', 'Important dates section', 'Elastic closure'],
    stock: 27,
    createdAt: new Date('2023-01-25'),
    updatedAt: new Date('2023-01-25'),
  },
  {
    id: '5',
    name: 'Luxury Leather Journal',
    description: 'Handcrafted genuine leather journal with refillable pages. A timeless accessory for writers and travelers.',
    price: 49.99,
    images: [
      '/pics/gabrielle-henderson-M4lve6jR26E-unsplash.jpg',
      '/pics/alireza-zarafshani-yhwzIx1YxqU-unsplash.jpg',
    ],
    category: 'premium',
    features: ['Genuine leather cover', 'Refillable', '100 pages', 'Handcrafted', 'Includes pen holder'],
    stock: 10,
    createdAt: new Date('2023-02-01'),
    updatedAt: new Date('2023-02-01'),
  },
  {
    id: '6',
    name: 'Waterproof Outdoor Notebook',
    description: 'All-weather notebook with waterproof pages. Ideal for outdoor adventures and field notes.',
    price: 22.99,
    images: [
      '/pics/ashley-west-edwards-zwmkMkJ2Qi4-unsplash.jpg',
      '/pics/ian-schneider-8COAUK8ckv8-unsplash.jpg',
    ],
    category: 'specialty',
    features: ['Waterproof pages', 'Durable cover', '48 pages', 'Tear-resistant', 'Write in any weather'],
    stock: 15,
    createdAt: new Date('2023-02-05'),
    updatedAt: new Date('2023-02-05'),
  },
  {
    id: '7',
    name: 'Leather-Bound Journal',
    description: 'Authentic Bangladeshi leather-bound journal with handstitched binding and premium cotton pages.',
    price: 34.99,
    images: [
      '/pics/pavel-polivka-7lS8ChNKsFs-unsplash.jpg',
      '/pics/jeff-james-wgm_RD92nhE-unsplash.jpg',
    ],
    category: 'leather-bound',
    features: ['Genuine leather', 'Handstitched binding', '120 pages', 'Refillable', 'Artisan crafted'],
    stock: 22,
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date('2023-02-15'),
  },
  {
    id: '8',
    name: 'Recycled Paper Notebook',
    description: 'Eco-friendly notebook made from 100% recycled materials. Gentle on the environment without compromising on quality.',
    price: 9.99,
    images: [
      '/pics/glenn-carstens-peters-ZWD3Dx6aUJg-unsplash.jpg',
      '/pics/premium_photo-1685134731677-1f5021c1f764.avif',
    ],
    category: 'recycled',
    features: ['100% recycled paper', 'Biodegradable cover', '80 pages', 'Plant-based inks', 'Tree-free production'],
    stock: 50,
    createdAt: new Date('2023-02-20'),
    updatedAt: new Date('2023-02-20'),
  },
  {
    id: '9',
    name: 'Children\'s Drawing Notebook',
    description: 'Specially designed notebook for children with thick pages that resist tearing and bleeding. Perfect for young artists.',
    price: 7.99,
    images: [
      '/pics/kelly-sikkema-iiaUVel-cJE-unsplash.jpg',
      '/pics/joanna-kosinska-I3adKpDNAjM-unsplash.jpg',
    ],
    category: 'kids',
    features: ['Thick 120gsm paper', 'Rounded corners', '60 pages', 'Non-toxic materials', 'Colorful design'],
    stock: 35,
    createdAt: new Date('2023-03-01'),
    updatedAt: new Date('2023-03-01'),
  },
  {
    id: '10',
    name: 'Traditional Bangladeshi Notebook',
    description: 'Handcrafted using traditional Bangladeshi techniques with locally-sourced materials. Each piece is unique.',
    price: 18.99,
    images: [
      '/pics/annie-spratt-XkSrMoHhJ30-unsplash.jpg',
      '/pics/aaron-burden-AXqMy8MSSdk-unsplash.jpg',
    ],
    category: 'traditional',
    features: ['Handmade paper', 'Traditional binding', '100 pages', 'Unique patterns', 'Cultural motifs'],
    stock: 25,
    createdAt: new Date('2023-03-05'),
    updatedAt: new Date('2023-03-05'),
  },
  {
    id: '11',
    name: 'Artist\'s Sketchbook',
    description: 'Premium heavy-weight paper ideal for all artistic media from pencil to light watercolor and gouache.',
    price: 29.99,
    images: [
      '/pics/joanna-kosinska-I3adKpDNAjM-unsplash.jpg',
      '/pics/aaron-burden-xG8IQMqMITM-unsplash.jpg',
    ],
    category: 'art',
    features: ['220gsm paper', 'Spiral bound', '50 pages', 'Acid-free', 'Suitable for multiple media'],
    stock: 30,
    createdAt: new Date('2023-03-10'),
    updatedAt: new Date('2023-03-10'),
  },
  {
    id: '12',
    name: 'Pocket Memo Pad',
    description: 'Ultra-portable memo pad that fits in your pocket. Perfect for quick notes and ideas on-the-go.',
    price: 4.99,
    images: [
      '/pics/kelly-sikkema-9OGNpJPVMZ8-unsplash.jpg',
      '/pics/glenn-carstens-peters-ZWD3Dx6aUJg-unsplash.jpg',
    ],
    category: 'pocket',
    features: ['Small 3x5" size', 'Soft cover', '48 pages', 'Perforated pages', 'Rounded corners'],
    stock: 60,
    createdAt: new Date('2023-03-15'),
    updatedAt: new Date('2023-03-15'),
  },
];

export const categories = [
  { id: 'all', name: 'All Notebooks' },
  { id: 'ruled', name: 'Ruled Notebooks' },
  { id: 'dot-grid', name: 'Dot Grid Journals' },
  { id: 'sketch', name: 'Sketchbooks' },
  { id: 'planner', name: 'Planners' },
  { id: 'premium', name: 'Premium Journals' },
  { id: 'specialty', name: 'Specialty Notebooks' },
  { id: 'leather-bound', name: 'Leather-Bound' },
  { id: 'recycled', name: 'Eco-Friendly' },
  { id: 'kids', name: 'Children\'s' },
  { id: 'traditional', name: 'Traditional' },
  { id: 'art', name: 'Artist Series' },
  { id: 'pocket', name: 'Pocket Size' },
];
